#!/usr/bin/env bash
# Write a Bash script that displays numbers from 1 to 20
i=0
while [ $i -lt 20]; do
case $i in
3)
echo $i
echo "bad luck from China"
;;
8)
echo $i
echo "bad luck from Japan"
;;
16)
echo $i
"bad luck from Italy"
;;
*)
echo $i;;
esac
((i++))
done
