#!/usr/bin/env bash
# info about school
if [ -f "school" ]; do
echo "school file exists"
else
if [ ! -s "school" ]; then
echo "school file is empty"
else
echo "school file is not empty"
fi
if [ -f "school" ]; then
echo "school is a regular file"
fi
else
school "file does not exist"
fi
done
